### ISSUE TITLE
Critical error which makes Log In impossible to some wallets

### ISSUE THREAD

**Issue by myclownfish** [blockchain/blockchain-wallet-v4-frontend#3170] opened 2021-05-08 13:45 UTC
## Description
On some accounts it has been impossible to connect since yesterday release.
Login to the site triggers a JavaScript error, which results from an impossible access to the account from the Web wallet (it is therefore no longer possible to send USDT because we can only send via the Web wallet).
Log in to the Mobile app work fine, but impossible to send USDT that makes this error really critical.

VERY CRITICAL BUG.

## Reproduction Steps
You can just try to connect to see the errors, it was impossible to connect with one of my account while it was still possible with others accounts. It's very weird.

## Screenshots/Logs
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    _pipe https://login.blockchain.com/vendor.96b947fc3c.js:2
    _arity https://login.blockchain.com/vendor.96b947fc3c.js:2

### Web console
![log 1](https://i.ibb.co/VgKcW67/Screenshot-2.jpg)

The last XHR request is performed to : https://api.blockchain.info/metadata/ (GET)

### Last XHR requests before the error
![log 2](https://i.ibb.co/ynJWVLL/Screenshot-3.jpg)

**Comment by masterQW** [comment] 2021-05-08 19:23
I am seeing the same problem.
This is a very big problem. I cannot enter my wallet, but I can enter any other, recently created.

**Comment by myclownfish** [comment] 2021-05-08 20:37
> 
> 
> I am seeing the same problem.
> This is a very big problem. I cannot enter my wallet, but I can enter any other, recently created.

Yes it's very weird, I hope they will fix that soon, I have tens of thousands of USDT blocked...
This is very critical, hoping that they will fix this problem very soon.

**Comment by plondon** [comment] 2021-05-08 20:45
I'm trying to reproduce this error but I'm unable to. Can you provide some more info on the wallets such as if you had paired to ios or android?

**Comment by plondon** [comment] 2021-05-08 21:06
I believe the issue is happening around parsing the eth metadata entry. There is a special login link you can use that will generate more logs to the console. 

1. navigate in a new tab to https://login.blockchain.com/#/open/log-level?level=verbose
2. open console
3. attempt login

Hopefully if it's an issue w/ metadata as I said above we can uncover more about the issue.

If you want to email me results: philip at blockchain.com

**Comment by myclownfish** [comment] 2021-05-08 23:10
> 
> 
> I believe the issue is happening around parsing the eth metadata entry. There is a special login link you can use that will generate more logs to the console.
> 
>     1. navigate in a new tab to https://login.blockchain.com/#/open/log-level?level=verbose
> 
>     2. open console
> 
>     3. attempt login
> 
> 
> Hopefully if it's an issue w/ metadata as I said above we can uncover more about the issue.
> 
> If you want to email me results: philip at blockchain.com



> metadata

Thank you for your answer Philippe, I have 3 crypto: ethereum, bitcoin and USDT. 
It is impossible to log in to the Web Wallet even with the mobile-login (Pair Web Wallet), and indeed it seems that it blocks just after the metadata requests.

Everything works normally with the mobile app, so I think it's a frontend problem "blockchain-wallet-v4-frontend".

I sent you an email to get the detailed logs following your steps.

**Comment by plondon** [comment] 2021-05-08 23:27
philip@blockchain.com ?

**Comment by myclownfish** [comment] 2021-05-08 23:38
> [philip@blockchain.com](mailto:philip@blockchain.com)

Sent :)

**Comment by plondon** [comment] 2021-05-10 18:10
https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/3172/files

was merged to help you with login, the kvstore entry is still broken but at least you can login now

**Comment by plondon** [comment] 2021-05-11 18:03
I'll close this for now.

**Closed by plondon** 2021-05-11 18:03 UTC
