### ISSUE TITLE
http://blockchain-stellar.info is a phishing site

### ISSUE THREAD

**Issue by DnHariz** [blockchain/blockchain-wallet-v4-frontend#1213] opened 2018-11-28 05:45 UTC
## Bug Report

I have a XLM claim email in my email as in my screenshot. after I click I fill in 12 backup phrases but after I claim my account suddenly unverified again. ! Is the site in my screenshot really a blockchain website or a phishing site? if that's official there must be a bug there. if it's a phishing site, please reset my backup phrase

## Screenshoot
![screenshot_2018-11-28-12-29-03-901_com google android gm](https://user-images.githubusercontent.com/45255913/49131490-fdea1880-f30a-11e8-9779-f088b84e02ef.png)
![screenshot_2018-11-28-12-27-09-821_com android chrome](https://user-images.githubusercontent.com/45255913/49131603-676a2700-f30b-11e8-8210-2cbcbe1ecbc5.png)
![screenshot_2018-11-28-12-27-20-124_com android chrome](https://user-images.githubusercontent.com/45255913/49131607-6c2edb00-f30b-11e8-8fbb-414d75778f96.png)
![screenshot_2018-11-28-12-27-55-946_com android chrome](https://user-images.githubusercontent.com/45255913/49131622-72bd5280-f30b-11e8-8ca7-f87add86c047.png)

**Comment by plondon** [comment] 2018-11-28 12:56
blockchain-stellar.info is a phishing site :(

**Comment by plondon** [comment] 2018-11-28 12:58
Did you have any funds associated with your wallet? By giving away your mnemonic they have access to any funds associated with that wallet. Hopefully you don't have funds on it

**Comment by DnHariz** [comment] 2018-11-28 13:29
@plondon how do i change my mnemonic or reset my mnemonic ? please help me !

my ID: c81239ed-d83f-4e9a-91ba-e400f9fd9262.

**Comment by Mondei1** [comment] 2018-11-28 13:35
You can create a new account (or Bitcoin wallet with a software) and tranfer all your funds to the new account. Your Blockchain account is safe but not your Bitcoin wallet anymore. Remind, never give your 12 words away!

**Comment by DnHariz** [comment] 2018-11-28 13:44
@Mondei1 ok please delete my account . My gmail : dnhariz@gmail.com . I will register with that email again! because I have not claimed XML bounty . This phishing is very dangerous. looks very original from the blockchain! until uploading a video on youtube with the name blockchain
![screenshot_2018-11-28-20-41-35-364_com google android gm](https://user-images.githubusercontent.com/45255913/49155786-660e1e00-f34e-11e8-8f82-12fcf89fd3e3.png)

**Comment by Mondei1** [comment] 2018-11-28 14:35
I'm not part of the team, just a volunteer. You can double assign account to one email.

**Comment by DnHariz** [comment] 2018-11-28 17:17
@plondon there is no reward for me after reporting a dangerous phishing site ? Lol 
Maybe there is . sincerely 1K9kLVK499zpDM1VZgRtHrRibUuKy1eeTi

Thanks 😆

**Comment by plondon** [comment] 2018-11-29 12:56
Closing since site is reported and shows a 'deceptive site ahead' alert. @DnHariz we have a bug bounty program: https://hackerone.com/blockchain. But this was not a bug

**Closed by plondon** 2018-11-29 12:56 UTC

**Comment by DnHariz** [comment] 2018-11-30 10:33
@plondon Report New phising site . And I still wait XLM since 11day
![screenshot_2018-11-30-17-29-48-948_com android chrome](https://user-images.githubusercontent.com/45255913/49283999-e7d48780-f4c5-11e8-8a7d-e46b737b01f1.png)
